version: '3.4'

services:
    database-ixui:
        image: mysql
        container_name: database-ixui
        expose:
            - 3306
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ixui
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=ixui
